const RGB_CD_BLAU = "rgb(10 , 85 , 140)";
const RGB_CD_TUERKIS = "rgb(50 , 180 , 200)";
const RGB_CD_GRUEN = "rgb(0 , 145 , 90)";
const RGB_CD_HELLGRUEN = "rgb(110 , 165 , 60)";
const RGB_CD_GELB = "rgb(250 , 190 , 0)";
const RGB_CD_ORANGE = "rgb(240 , 120 , 35)";
const RGB_CD_ROT = "rgb(195 , 5 , 50)";
const RGB_CD_VIOLETT = "rgb(120 , 100 , 165)";

exports.RGB_CD_BLAU = RGB_CD_BLAU;
exports.RGB_CD_TUERKIS = RGB_CD_TUERKIS;
exports.RGB_CD_GRUEN = RGB_CD_GRUEN;
exports.RGB_CD_HELLGRUEN = RGB_CD_HELLGRUEN;
exports.RGB_CD_GELB = RGB_CD_GELB;
exports.RGB_CD_ORANGE = RGB_CD_ORANGE;
exports.RGB_CD_ROT = RGB_CD_ROT;
exports.RGB_CD_VIOLETT = RGB_CD_VIOLETT;

const RGB_VALS_CD_BLAU = "10 , 85 , 140";
const RGB_VALS_CD_TUERKIS = "50 , 180 , 200";
const RGB_VALS_CD_GRUEN = "0 , 145 , 90";
const RGB_VALS_CD_HELLGRUEN = "110 , 165 , 60";
const RGB_VALS_CD_GELB = "250 , 190 , 0";
const RGB_VALS_CD_ORANGE = "240 , 120 , 35";
const RGB_VALS_CD_ROT = "195 , 5 , 50";
const RGB_VALS_CD_VIOLETT = "120 , 100 , 165";

exports.RGB_VALS_CD_BLAU = RGB_VALS_CD_BLAU;
exports.RGB_VALS_CD_TUERKIS = RGB_VALS_CD_TUERKIS;
exports.RGB_VALS_CD_GRUEN = RGB_VALS_CD_GRUEN;
exports.RGB_VALS_CD_HELLGRUEN = RGB_VALS_CD_HELLGRUEN;
exports.RGB_VALS_CD_GELB = RGB_VALS_CD_GELB;
exports.RGB_VALS_CD_ORANGE = RGB_VALS_CD_ORANGE;
exports.RGB_VALS_CD_ROT = RGB_VALS_CD_ROT;
exports.RGB_VALS_CD_VIOLETT = RGB_VALS_CD_VIOLETT;